# -*- coding: utf-8 -*-
"""logistic_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WAI3olvotuIwwn0k7-H9VRA0mH7VkauN
"""

import streamlit as st
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# -----------------------------------
# Page Configuration
# -----------------------------------
st.set_page_config(
    page_title="House Price Prediction",
    page_icon="🏠",
    layout="centered"
)

st.title("🏠  Insurance  prediction")
st.write("Predict wether a person is likely to buy insurance based on age using Logistic  Regression")

# -----------------------------------
# Load Dataset
# -----------------------------------
df = pd.read_csv("insurance_data.csv")

st.subheader("Dataset")
st.dataframe(df)

# -----------------------------------
# Train Model
# -----------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    train_size=0.8,
    random_state=42
)
model = LogisticRegression()
model.fit(X_train, y_train)


# -----------------------------------
# User Input
# -----------------------------------
st.subheader("Enter  Age")

age = st.number_input(
    "Age (in Years)",
    min_value=15,
    max_value=80,
    value=18,
    step=1
)

# -----------------------------------
# Prediction
# -----------------------------------
if st.button("Predict Insurance"):

    prediction = model.predict([[age]])
    
    if prediction[0] == 1:
      st.success("✅ The person is likely to buy insurance.")
    else:
     st.error("❌ The person is unlikely to buy insurance.")

# -----------------------------------
# Model Information
# -----------------------------------
st.subheader("Model Details")

st.write("Coefficient:", model.coef_[0])
st.write("Intercept:", model.intercept_)
